name: Build Custom Launcher

on:
  workflow_dispatch: # Это дает ту самую кнопку запуска вручную!

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apks
          path: build/app/outputs/flutter-apk/*.apk
