name: Build Custom Launcher

on:
  workflow_dispatch: # Кнопка ручного запуска

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y make depdep # Ставим make для выполнения команд из Makefile

      - name: Install Dependencies
        run: |
          flutter pub get

      - name: Generate Code (Hiddify Way)
        run: |
          make gen # Запускаем родной генератор Hiddify, который прописан в Makefile

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apks
          path: build/app/outputs/flutter-apk/*.apk
